### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by gripxtech** [adolfintel/muhtriangles-android#1]
hello sir the project is imported succesfully but when we run project the gets hang i really want to work on this project any suggestions for performance

**Comment by adolfintel** [comment]
Hi.
What exactly hangs? Android studio? Or does the app run slowly?

**Comment by gripxtech** [comment]
App runs slowly sir

**Comment by adolfintel** [comment]
If it's running slowly on the emulator, make sure you have Intel HAXM installed and enabled, as well as hardware acceleration. Without these two, it will run badly.
If it's running slowly on real hardware, I suggest you check your build environment, maybe reinstall Android Studio and the SDK, some setting might be messed up.

**Comment by gripxtech** [comment]
Thanks For  Support Sir. Issue Solved After Cleaning Mobile Space
